version: '{build}'
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
configuration:
- Release
artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- appveyor-retry dotnet restore zipkin4net.sln --verbosity Minimal
build_script:
- dotnet build "zipkin4net.sln" -c %CONFIGURATION%
after_build:
- cmd: IF "%APPVEYOR_REPO_TAG%" == "true" (dotnet pack /p:PackageVersion="%APPVEYOR_REPO_TAG_NAME%" "Src\zipkin4net\Src\zipkin4net.csproj" -c %CONFIGURATION% --no-build --no-restore -o %APPVEYOR_BUILD_FOLDER%\artifacts)
- cmd: IF "%APPVEYOR_REPO_TAG%" == "true" (dotnet pack /p:PackageVersion="%APPVEYOR_REPO_TAG_NAME%" "Src\zipkin4net.middleware.aspnetcore\Src\zipkin4net.middleware.aspnetcore.csproj" -c %CONFIGURATION% --no-build --no-restore -o %APPVEYOR_BUILD_FOLDER%\artifacts)
- cmd: IF "%APPVEYOR_REPO_TAG%" == "true" (dotnet pack /p:PackageVersion="%APPVEYOR_REPO_TAG_NAME%" "Src\zipkin4net.middleware.owin\Src\zipkin4net.middleware.owin.csproj" -c %CONFIGURATION% --no-build --no-restore -o %APPVEYOR_BUILD_FOLDER%\artifacts)
test_script:
- dotnet test "Src/zipkin4net/Tests/zipkin4net.Tests.csproj" -c %CONFIGURATION%
- dotnet test "Src/zipkin4net.middleware.owin/Tests/zipkin4net.middleware.owin.Tests.csproj" -c %CONFIGURATION%
cache:
- '%USERPROFILE%\.nuget\packages'
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: /U9jebmr13NyJPUqTEItqBKxMEVUZWqD5scotuC33CVbfCevG+oepVUv/kvqPMJN
  on:
    branch: master
    appveyor_repo_tag: true
